### ISSUE TITLE
Rollup plugin processes imported typescript files as javascript

### ISSUE THREAD

**Issue by foobardevpro** [theseanl/tscc#108]
Hi.

I've encountered two different ways to produce this issue:

**1. Parentheses in path**
```
// work(space/src/root.ts
import './test'
```
```
// work(space/src/test.ts
const x: number = 123
```
```
// work(space/tsconfig.json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs"
	}
}
```
```
// work(space/tscc.spec.json
{
	"modules": {
		"dist/root": "src/root.ts"
	},
	"prefix": "./"
}
```
```
// work(space/watch.js
const rollup = require('rollup')
const tscc = require('@tscc/rollup-plugin-tscc').default
const typescript = require('rollup-plugin-typescript')
const serve = require('rollup-plugin-serve')
const livereload = require('rollup-plugin-livereload')

const watcher = rollup.watch({
	output: {
		dir: '.',
		format: 'iife'
	},
	plugins: [
		serve({
			open: true,
			watch: 'dist',
			contentBase: 'dist',
			port: 8080
		}),
		livereload(),
		tscc({
			specFile: 'tscc.spec.json'
		}),
		typescript({
			tsconfig: 'tsconfig.json'
		})
	]
})

watcher.on('event', (e) => {
	if (e.code == 'END') {
		console.log('Build successful.')
	} else if (e.code == 'ERROR') {
		console.log('Error description:')
		console.log(e)
	}
})
```

Notice there is a deliberate parenthesis in the folder name.

If I run ``node ./watch.js``, I receive the following error:
```
Error description:
{
  code: 'ERROR',
  error: Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
      at error (D:\*****\work(space\node_modules\rollup\dist\rollup.js:5351:30)
      at Module.error (D:\*****\work(space\node_modules\rollup\dist\rollup.js:9631:9)
      at tryParse (D:\*****\work(space\node_modules\rollup\dist\rollup.js:9539:16)
      at Module.setSource (D:\*****\work(space\node_modules\rollup\dist\rollup.js:9856:33)
      at D:\*****\work(space\node_modules\rollup\dist\rollup.js:12645:20
      at async Promise.all (index 0)
      at async Promise.all (index 0)
      at async Promise.all (index 0)
      at async Promise.all (index 0) {
    code: 'PARSE_ERROR',
    parserError: SyntaxError: Unexpected token (1:7)
        at Object.pp$4.raise (D:\*****\work(space\node_modules\acorn\dist\acorn.js:2836:15)
        at Object.pp.unexpected (D:\*****\work(space\node_modules\acorn\dist\acorn.js:689:10)
        at Object.pp$1.parseVar (D:\*****\work(space\node_modules\acorn\dist\acorn.js:1230:14)
        at Object.pp$1.parseVarStatement (D:\*****\work(space\node_modules\acorn\dist\acorn.js:1092:10)
        at Object.pp$1.parseStatement (D:\*****\work(space\node_modules\acorn\dist\acorn.js:842:19)
        at Object.parseStatement (D:\*****\work(space\node_modules\rollup\dist\rollup.js:11617:30)
        at Object.pp$1.parseTopLevel (D:\*****\work(space\node_modules\acorn\dist\acorn.js:746:23)
        at Object.parse (D:\*****\work(space\node_modules\acorn\dist\acorn.js:553:17)
        at Function.parse (D:\*****\work(space\node_modules\acorn\dist\acorn.js:576:37)
        at tryParse (D:\*****\work(space\node_modules\rollup\dist\rollup.js:9529:23) {
      pos: 7,
      loc: [Position],
      raisedAt: 8
    },
    pos: 7,
    loc: {
      column: 7,
      file: 'D:/*****/work(space/src/test.ts',
      line: 1
    },
    frame: '1: const x: number = 123\n          ^',
    watchFiles: [
      'D:\\*****\\work(space\\src\\root.ts',
      'D:/*****/work(space/src/test.ts'
    ]
  }
}
```

If I change the contents of ``test.ts`` from typescript to javascript, for example:
```
// work(space/src/test.ts
const x = 123
```
rollup plugin will build successfully.

I've ran into this issue because I had copied my workspace and had like "workspace (2)"...

**2. Importing files outside of workspace**

If I rename ``work(space`` to ``workspace`` the issue above will be fixed.
However:
If I move ``test.ts`` up two levels, to be next to ``workspace`` folder, and change contents of ``root.ts`` to:
```
// workspace/src/root.ts
import '../../test'
```
the same error will occur: the file ``test.ts`` will be processed as javascript file, rather than typescript.
And, if I strip the typing as such:
```
// test.ts
const x = 123
```
the build will succeed.

(in my personal project, I have folders ``client``, ``server``, ``common``, and I need to be able to navigate up from ``client`` and ``server``, to import shared typescript files from ``common``)

**Comment by theseanl** [comment]
Your `test.ts` file is not a "module", it does not export or import anything so it is a "script", so you can't `import 'test.ts'`. If you change it to a module, does the issue still persist?

**Comment by foobardevpro** [comment]
Hi.

Just checked, both issues still persist, with something like:
```
// test.ts
const x: number = 1

export default x
```
```
// root.ts
import test from (relevant path for scenario 1 or 2)
console.log(test)
```

p.s. have you seen my follow up comment in the issue thread for rollup with nested source files? maybe it's relevant somehow for this issue too?

**Comment by theseanl** [comment]
Your samples lack `tsconfig.json` file which is required for tscc. Could you provide a sample repository demonstrating the issue?

**Comment by theseanl** [comment]
This is not an issue with tscc. This is caused by some careless codes of [`rollup-pluginutils` package](https://github.com/rollup/rollup-pluginutils) that `rollup-plugin-typescript` uses. It filters `.tsx?` files among rollup inputs by using a `createFilter` functionality of `rollup-pluginutils`.

The glob pattern created by `rollup-pluginutils` merely concatenates input pattern with a path of the current working directory.

Case 1 - the current working directory's path contains a character that needs to be escaped to used as a glob pattern.
Case 2 - the pattern is some thing like `{current_working_directory}/*.tsx?`, so it does not match any file that is not in the current working directory.

There is even a similar issue reported in `rollup-pluginutils` repository: https://github.com/rollup/rollup-pluginutils/issues/57
