### ISSUE TITLE
TSCC not compatible with chalk 3.0.0

### ISSUE THREAD

**Issue by amoerie** [theseanl/tscc#141]
Running tscc with chalk 3.0.0 produces an error, because chalk_1.default is undefined in the tscc main js file.

The solution to work around this problem is using yarn resolutions or manually editing an NPM shrinkwrap file to use chalk 2.4.2

The package json definition does not stop npm from using chalk 3.0.0, so an immediate fix could be to lock down the version.

**Comment by theseanl** [comment]
After running tsc again it gets correct transpilation. Not sure why there was `chalk.default` from the beginning. I'll push new versions after updating tsickle.

**Comment by amoerie** [comment]
Great, thanks!

**Comment by theseanl** [comment]
Done, please check with 0.4.8!
