### ISSUE TITLE
 Module name node_modules._types.react_dom.test_utils.index.d was not provided as a closure compilation source

### ISSUE THREAD

**Issue by amoerie** [theseanl/tscc#143]
Trying to get a React sample running, but I keep getting this error. (see title)

All libraries are defined as externals, as prescribed, so this seems to purely related to type information.

You can import code from "react-dom/test-utils", but our application never does, so I'm a little lost on where this error comes from and how it can be resolved.

**Comment by theseanl** [comment]
Do you have `import _ from 'react/test-utils'` statement in files that are passed to the compiler? Usually test files do not need to be minified, so I suspect that you've misconfigured tscc that it includes test files for compilation.

If not, do you have 
```json
{
    "external": {
        "react-dom/test-utils": "ReactTestUtils"
    }
}
```
in your spec file? It seems that the react-dom/test-utils package is a separate module that is not re-exported from main `react-dom` module.

**Comment by amoerie** [comment]
🤦‍♂️ We actually had an import of react-dom/test-utils in some domain class by accident, my sincerest apologies!
