### ISSUE TITLE
Typescript CSS .css.d.ts configuration

### ISSUE THREAD

**Issue by capt-obvious** [theseanl/tscc#173]
How should I configure the tscc.spec.json to proper recognize XXXX.css.d.ts files?

```
TSCC: Module name src.routes.home.style.css.d was not provided as a closure compilation source
TSCC: The compilation has terminated with an error.
```

**Comment by capt-obvious** [comment]
I'm attempting to use TSCC to compile the preact cli template for typescript: https://github.com/preactjs-templates/typescript

**Comment by theseanl** [comment]
I can only provide some general remarks -- You need to somehow provide such files as tscc compilation sources. It seems that the default webpack build uses some loaders that converts `.css` files into js modules. To use it with tscc, you somehow need to convert them to js modules first and feed them. If you have a demo and a precise step to reproduce, I may take a look.
