### ISSUE TITLE
noEmitOnError=true has no effect

### ISSUE THREAD

**Issue by aminya** [theseanl/tscc#305]
I want to suppress the errors of my typescript project and build it using `tscc`, but setting `noEmitOnError=true` has no effect!

**Comment by theseanl** [comment]
Do you mean `noEmitOnError=false`? If this flag is set to `true`, errors won't be suppressed and outputs wont' be generated.

Currently tscc does not produce any output when there are errors typescript compilation step. The "demo" package of tsickle was written in this way so tscc just followed it. I think anyway if you have type errors, the generated closure-annotated js can be problematic to be fed to closure compiler, so it does not make much sense to support `noEmitOnError=false` behavior.

**Comment by aminya** [comment]
I think so. Having such a limitation is totally dependant on the tsconfig. You can write tsconfig such a way that no error is produced. Terser, for example, reaches a very good compilation without any type of information, so Closure Compiler should support this too.

So if I set this to false, will `tscc` work?

**Comment by theseanl** [comment]
> So if I set this to false, will `tscc` work?

Yes in principle. regardless of how `noEmitOnError` flag is set, tscc will behave like tsc with `noEmitOnError=true`.
