### ISSUE TITLE
Is it possible to somehow generate external spec automatically and wire in with webpack?

### ISSUE THREAD

**Issue by pbadenski** [theseanl/tscc#387]
We have a pretty large project with lots of dependencies. Since webpack is already aware managing dependencies bundling is it should be possible to automate generation of external spec.

Since I don't have enough knowledge to answer this - is what I'm describing even possible?
Is it in the scope of this project?
Is anyone aware of a project that might be addressing this? (I'm only aware of tsickle-loader, which I personally found it very difficult to use).

**Comment by theseanl** [comment]
I don't understand a problem you are describing. Regarding the `external` key of spec, isn't this information already available from `package.json` and webpack config files? It would depend on how you are planning to use tscc compilation output. Maybe you are going to feed the output to webpack again?

**Comment by pbadenski** [comment]
The way I understand, at the moment you need to manually write external keyspec:
```
{
    "external": {
        "react": "React",
        "react-dom": "ReactDOM",
    }
}
```
Then you need to provide a separate script which loads these dependencies into a global space. With large projects and large number of dependencies this can be quite a labourous task. I wonder if this can be automated with webpack?

**Comment by theseanl** [comment]
Sorry, but I don't think I understand the situation you are describing. It would be helpful if you could provide pointers to some public repository containing such a build setup. If this is about creating some webpack plugins, maybe someone who is more well-versed in webpack echosystem would be more suitable for such a task.
