### ISSUE TITLE
TSCC displays uninformative error when tsconfig.json is missing

### ISSUE THREAD

**Issue by ctjlewis** [theseanl/tscc#436]
# Repro
1. Install from NPM with `yarn global add @tscc/tscc`.
2. Create a project _without_ a `tsconfig.json`.
3. Run `tscc`.

```none
$ tscc
TS: error TS5083: Cannot read file ''.
```

This is not useful and prevents the user from knowing what is causing the problem.  

When fixed, it displays the correct error:
```none
$ tscc
TSCC: Cannot find tsconfig at .
TSCC: The compilation has terminated with an error.
```

This would be fixed by the rejected PR branch, which I will resubmit once more.

**Comment by theseanl** [comment]
This is fixed in 0.6.3 by #483.
