### ISSUE TITLE
JSC_GOOG_MODULE_MISPLACED

### ISSUE THREAD

**Issue by avery-laird** [theseanl/tscc#490]
Hello,

I'm using tscc to run one typescript file through the closure compiler. My spec file looks like this:
```
{
  "modules": {
    "<name>": "path/to/<name>.ts"
  },
  "compilerFlags": {
    "externs": "path/to/<name>_extern.js",
    "language_out": "ECMASCRIPT_2017",
    "compilation_level": "ADVANCED"
  }
}
```
I'm getting the following trace:
```
ClosureCompiler: path/to/<name>.js.tsickle:164:0: ERROR - [JSC_GOOG_MODULE_MISPLACED] goog.module() call must be the first statement in a file.
  164| goog.module('path/to.<name>$.ts');
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)


✖ Closure compiler error
TSCC: Closure compiler has exited with code 1
TSCC: The compilation has terminated with an error.
```

I've tried without using the externs argument, giving the same result. It seems like this might be a code generation issue. Any ideas on how to move forward?
Thanks for any help!

**Comment by theseanl** [comment]
Hi, most likely, it is transpiling non-modules and typescript helper codes are inserted at the beginning of the files. I badly need to implement https://github.com/theseanl/tscc/issues/385!

**Comment by avery-laird** [comment]
Thanks for the quick response. Anything I can try on my end to prevent this?

**Comment by theseanl** [comment]
You should only transpile modules, which is characterized by a presence of `import` or `export` statements.

**Comment by avery-laird** [comment]
that seems to be working. Thanks!
