### ISSUE TITLE
Cannot write file ... because it would overwrite input file

### ISSUE THREAD

**Issue by MrSonicMaster** [theseanl/tscc#499]
Using the prefix option, which should tell the compiler to write to a different directory, does not stop it from trying to write files into the source folder - causing this error message.

I have tried this config
```json
{
    "modules": {
        "out": {
            "entry": "./entrypoint.ts"
        }
    },
    "prefix": "./buildstuff/"
}
```

as well as setting the modules option to this
```json
"modules": {
        "index": "./entrypoint.ts"
},
```

neither work for me, am I misunderstanding something?

**Comment by theseanl** [comment]
Hi, I cannot reproduce an error with the spec files you have provided. Could you provide more detailed steps to reproduce the issue?
