### ISSUE TITLE
referencing other closure javascript

### ISSUE THREAD

**Issue by kyle-laracey** [theseanl/tscc#574]
First, thanks for developing this great tool. It makes using the Closure Compiler easy, which is saying a lot.

I have a Javascript file written in Closure-style Javascript that I would like to use from my Typescript project, but I can't seem to get it to work.  I've uploaded a minimal repro at https://github.com/kyle-laracey/tscc-with-closure-input. The Javascript looks like so:

`com/foo/bonjour.soy.js`:
```javascript
goog.provide('com.foo');
// ...
/**
 * <Closure JSdoc annotations...>
 */
com.foo.bonjour = function(/* ... */) { /* ... */};
```

I wrote a typings file for the Javascript so I could reference it from Typescript: 

`com/foo/bonjour.soy.d.ts`:
```typescript
declare module 'goog:com.foo' {
  export function bonjour(opt_data?: { [key: string]: any }): any;
}
```

And I reference it from my Typescript like so:

`com/foo/hello.ts`:
```typescript
///<reference path="./bonjour.soy.d.ts"/>
import { bonjour } from 'goog:com.foo';
document.write(bonjour());
```

Finally, I specify the Closure-Javascript file `extraSources`:

`tscc.spec.json`:
```json
{
  "modules": {
    "page": {
      "entry": "com/foo/hello.ts",
      "extraSources": ["com/foo/bonjour.soy.js"]
    }
  }
}
```

However, `tscc` gives the error

```
Module name com.foo was not provided as a closure compilation source
```

Can you give any guidance on this? Am I doing something wrong, or is this not supported by TSCC?

(I also have an alternative approach in the `alt` branch of the repro repo in which I got rid of the typings file and just add a typescript declaration for `bonjour` inside `hello.ts` itself, but that doesn't work. I'm not exactly sure why.)

Thanks.

**Comment by theseanl** [comment]
Hi, thank you for bringing this up. There was a field "jsFiles" in the spec file, which was intended for such use cases, but hasn't been tested. I just fixed it up and added a bit of documentation.

`extraSources` files are force-included in the compilation even if those are never referenced in other files, but they are also not used to determine dependency among compilation sources. If they are to be used to determine dependency, there would be no point to include them as a separate sub-field of modules flag, for anyway their correct position among chunks can be determined by their position in the dependency graph.

In contrast, files indicated in `jsFiles` will be included in the dependency graph, and will be used to determine the compiler flag.

Off-topic question, you seem to be using closure templates, which I have been always considering including first-class support to tscc. It'd be nice if you could share some thoughts about how it can be done.

I have always felt uneasy about them generating only `goog.provide`-style closure js. Also, as of now I have to manually write `.d.ts` file for closure-generated js files. Ideally,
 - soy-to-js compiler should generate `goog.module`-style js
 - there should be a compiler which generates `.d.ts` for each of `goog.module` output.

**Comment by kyle-laracey** [comment]
Thanks a lot, this was exactly what I needed. Given you said it hasn't been tested, I was surprised by the fact that it seems to "just work."

> Off-topic question, you seem to be using closure templates, which I have been always considering including first-class support to tscc. It'd be nice if you could share some thoughts about how it can be done.
>
> I have always felt uneasy about them generating only `goog.provide`-style closure js. Also, as of now I have to manually write `.d.ts` file for closure-generated js files. Ideally,
> 
> * soy-to-js compiler should generate `goog.module`-style js
> * there should be a compiler which generates `.d.ts` for each of `goog.module` output.
>   Or, maybe there can be a soy-to-ts compiler.

I pushed a new branch ([`solution`](https://github.com/kyle-laracey/tscc-with-closure-input/tree/solution)) of the repro-repo with a fix for my problem using jsFiles and the Closure Template Compiler. I wrote up the general idea of what I did in [the commit message](https://github.com/kyle-laracey/tscc-with-closure-input/commit/fc793651e6352f7d2cb2e3fded7fe893c80641e1). 

I can't speak to the `goog.provide` issue. I only know that it seems to be (soft-) deprecated -- despite the fact that, IIRC, most of the Closure Library seems to still rely on it.

https://github.com/angular/clutz was a tool to generate `.d.ts` files from Closure Javascript. However it seems to be archived now.
