### ISSUE TITLE
TSCC can generate module names with '..', how to set rootDir

### ISSUE THREAD

**Issue by Mythra** [theseanl/tscc#599]
👋 Hey! Thanks for the great project! I'm attempting to write some rules to call `tscc` from within Bazel. Unfortunately, due to some of the paths of bazel we seem to be generating file paths with: `../../../../../lib/psion/eggsample/index.ts` which ends up causing closure compiler to barf on the TSCC input:

```
TSCC: --outDir option is ignored. Use prefix option in the spec file.
TSCC: --rootDir option is ignored. It will internally set to /.
TSCC: tsickle uses a custom tslib optimized for closure compiler. importHelpers flag is set.
ClosureCompiler: ../../../../../libs/psion/eggsample/index.js.tsickle:6:0: ERROR - [JSC_INVALID_NAMESPACE_OR_MODULE_ID] Namespace and module ID must be a dot-separated sequence of legal property identifiers. Found '$.$..$.$..$.$..$.$..$.$..libs.psion.eggsample.index$.ts'
  6| goog.module('$.$..$.$..$.$..$.$..$.$..libs.psion.eggsample.index$.ts');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)


✖ Closure compiler error
TSCC: Closure compiler has exited with code 1
TSCC: The compilation has terminated with an error.
Target //libs/psion:eggsample failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

Besides the `outDir` which I know how to fix -- i think (I just need to actually do it!), however `rootDir` I'm not sure how to workaround, as the comment on rootDir removal seems to imply there's no way to set this. How can I get TSCC, and it's associated things to ignore the `../../../../../` in the file path, or somehow set a root directory for tscc?

**Comment by theseanl** [comment]
Hi, could you provide a sample repository that I can reproduce the issue? I am not very familiar with Bazel and I don't get how you are exactly calling tscc with it.

There was a place in the code where it expect

**Comment by Mythra** [comment]
Hey! Sorry about the delay, I really tried digging in more to what's happening with Bazel here as it's an area i don't understand much, and wanted to provide helpful info. Unfortunately, my result didn't really work out well. I think it has to do something with how Bazel is doing symlinking + sandboxing. I think all in all there are three directories at play:

  1. A directory tscc runs from (which has symlinks to other directories).
  2. A directory I want tscc to output too (right now this is done with the `--output` directory which i know i need to change, i'd rather not spend too much time on that. I just want tscc + symlink to think it finished).
  3. The directory the source files are in.

I pushed up a simple example: https://github.com/Mythra/tscc-bazel-example The project can be built with: `bazel build //libs/eggsample:eggsample`, some of the args i've been using to debug are: `bazel build //libs/eggsample:eggsample --sandbox_debug -s --define=VERBOSE_LOGS=1`

Sorry I understand Bazel can be hard to understand sometimes, so any info I can provide please let me know. I still think setting a 'root directory' would be helpful here (to remove the `../../` which i understand why they are there in general), but I could be wrong.

**Comment by theseanl** [comment]
Hi, I wonder if you are still on the project. I added a bit of change so that such artificial module names are valid goog.module names when file paths are outside cwd. After changing the version of tscc, it seems that your sample example compiles (it now creates a different error `'libs/eggsample/eggsample.js' was not created`). I'm not sure if this is a suitable solution.

**Comment by Mythra** [comment]
Hi! 

I have admittedly stopped peaking at it for a bit, but am happy to dive in since you did this work.

Thank you so much! I'll update here in a bit!

**Comment by Mythra** [comment]
Yep! Sorry for the delay I ran into another slight issue, but that wasn't with TSCC. Thank you so much for the fix!
