### ISSUE TITLE
`/usr/bin/env: ‘node\r’: No such file or directory`

### ISSUE THREAD

**Issue by BrianLeishman** [theseanl/tscc#726]
I think the file has some Windows carriage returns in it?

Updating to the latest version on Ubuntu 22.04 like

```shell
yarn global add @tscc/tscc
tscc
```
And I get the

```
/usr/bin/env: ‘node\r’: No such file or directory
```
Changing the line endings with this
```shell
vim ~/.npm-packages/bin/tscc
```

and using 
```
:se ff=unix
:wq
```
fixed it for me

**Comment by theseanl** [comment]
Thank you for reporting it. It appears that I have invoked typescript compiler in Windows at some point while testing it.
Now there is `"newLine": "lf"` in the compiler option, it shouldn't happen anymore. Should be fixed with 0.9.2.
