### ISSUE TITLE
Using external library which contains typing

### ISSUE THREAD

**Issue by karadnized** [theseanl/tscc#757]
I've been trying to use [reflect-metadata](https://rbuckton.github.io/reflect-metadata/) but i'm unable to get compiled with ADVANCED compilation 

tscc.spec.json
```
 "external": {
    "reflect-metadata": "Reflect"
  }`
```

main.ts
`
import "reflect-metadata";
`

I see externs generated for the package but no source code generated.

**Comment by theseanl** [comment]
Hi, merely importing the package only assigns certain functions to the global namespace `Reflect`, and Closure Compiler sees no code that uses the newly defined functions, so it isn't a surprise that the output is empty.

Also, having an external module's global alias that is already declared somewhere in closure compiler's externs (like your choice of `Reflect`) causes externs generated by TSCC to collide with closure compiler's own. I'd say it's safe-ish, but the behavior on externs collision isn't documented anywhere.

I think you don't need to declare it in `external` key. If you have a reproduction steps with codes that makes an essential use of the `reflect-metadata` package, I can take a look.

**Comment by karadnized** [comment]
@theseanl https://github.com/karadnized/tscc-test-reflect

**Comment by theseanl** [comment]
And what's the issue with that repo? Tscc compiles the output just fine, and the output has the same behavior as the source.

**Comment by karadnized** [comment]
@theseanl The library should add functions the Reflect global. `[Reflect.defineMetadata](https://github.com/rbuckton/reflect-metadata/blob/master/Reflect.js#L233)` is not a native function. It will be added the library and that's what i don't see

**Comment by theseanl** [comment]
Well, a good virtue of every bug report is to provide an expected behavior and an actual behavior you are observing. It seems that you don't understand what `external` does.
