### ISSUE TITLE
ImportMeta compiler error after installing rollup

### ISSUE THREAD

**Issue by foobardevpro** [theseanl/tscc#99]
Hi.

I've made a simple demo that demonstrates this issue:
[https://github.com/foobardevpro/tscc-issues](https://github.com/foobardevpro/tscc-issues)

(this demonstration is in the same repo used for https://github.com/theseanl/tscc/issues/98#issue-512779678 but it deserves its own issue):

I'm not sure if it's easily solvable, but it seems worth mentioning, in case someone else runs into this error.

**Comment by theseanl** [comment]
Here is a description of what is happening:

 - Typescript's default library `lib.es5.d.ts` [contains](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L614) a declaration of an empty interface `ImportMeta`, which is a type of [`import.meta`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta). This is a keyword to be accessed in module codes which are unlikely to be a target use case of closure compiler.

 - `@types/node` package [contains](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts#L157) a declaration that extends the `ImportMeta` interface.

 - `rollup` has a dependency (not a devDependency!) `@types/node`.

 - Typescript [by default](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) includes every visible packages in `node_modules/@types` directory for compilation.

 - Hence tscc feeds `@types/node` to tsickle to generate externs, which contains a line `ImportMeta.prototype.url` that references an identifier that is present in Typescript but not in Closure compiler, causing an error.

Tsickle comes with a set of externs that are meant to bridge this gap, but I think not every such issue needs to be addressed there. Given that `ImportMeta` is not going to be used a lot in codebases that uses closure compiler or tscc, I think the sensible solution is to exclude `@types/node` from the compilation from user code by adding:
```jsonc
// tsconfig.json
{
    "compilerOptions": {
        "types": ["react"]
    }
}
```

If there are more use cases that encounters this `ImportMeta` name, this may needs to be addressed in tsickle.

**Comment by theseanl** [comment]
Now rollup does not have `@types/node` as a dependency.
